#!/bin/bash

cp ~/.zshrc .zshrc
cp ~/.zprofile .zprofile
cp ~/.zaliases .zaliases
cp ~/.config/Code/User/settings.json vscode/settings.json
cp ~/.config/Code/User/keybindings.json vscode/keybindings.json
